spring:
  application:
    name: data-sync
  datasource:
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123abc
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    connection-timeout: 30s

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sakura.demo.datasync.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# canal 配置
canal:
  port: 11111
  batch-size: 1000
  destination: example
#  https://github.com/alibaba/canal/wiki/AdminGuide    canal.instance.filter.regex配置
  filter: "my_db\\..*"
  username:
  password:
  base-package: com.sakura.demo.datasync.modal.document
  clazz-suffix: Document